### ISSUE TITLE
homework 005

### ISSUE THREAD

**Issue by kaochenlong** [kaochenlong/ntub-ruby-course2017#111]
學號：8306043
文章網址：http://kaochenlong.com/2017/10/23/have-you-met-elixir/

**Comment by leslie0726** [comment]
學號：10446004
文章網址：https://medium.com/@event1511252/ruby-java%E7%9A%84%E5%B0%8F%E8%A6%8B%E8%A7%A3-e1661fb90aae

**Comment by maryyu456** [comment]
學號：10446002
文章網址：https://medium.com/@mary.yu456/%E8%81%8A%E8%81%8Aruby%E8%88%87java%E4%B9%8B%E9%96%93%E7%9A%84%E5%B7%AE%E7%95%B0-f81cc4a25c44

**Comment by jerry0513** [comment]
學號：10446011
文章網址：https://medium.com/@zxcv860513/%E7%B8%AE%E6%B8%9B%E5%88%B0%E6%A5%B5%E8%87%B4%E7%9A%84ruby-4f7137cec8da

**Comment by chiaqingwu** [comment]
學號：10446011
文章網址：https://medium.com/@andrewwu_59643/different-from-ruby-95f07a241149

**Comment by 10446001** [comment]
學號：10446001
文章網址：https://medium.com/@chi19961202/what-is-the-different-between-java-and-ruby-32085361eb1d

**Comment by mushroomchen0429** [comment]
學號：10446013
文章網址：https://medium.com/@ShiXuanChen/%E7%BE%8E%E9%BA%97%E7%9A%84%E7%B4%85%E5%AF%B6%E7%9F%B3-ruby-6b3e10c6b77e

**Comment by Peggy10446003** [comment]
學號：10446003
文章網址：https://peishanntub.blogspot.tw/2017/11/ruby.html?spref=fb

**Comment by zhang-rongzhen** [comment]
學號：10636014
文章網址：https://medium.com/@jing1981jing1981/%E6%88%91%E7%9C%BC%E4%B8%AD%E7%9A%84ruby-83e1983c76f2

**Comment by changyuchieh** [comment]
學號 : 10636024
文章網址 : 
https://medium.com/@maymay51885188/%E5%B0%8Druby%E7%9A%84%E4%B8%80%E4%BA%9B%E8%A6%8B%E8%A7%A3-a9fcdc0dac48

**Comment by 10446012** [comment]
學號：10446012
文章網址：
https://medium.com/@mo359612/ruby-%E8%88%87-%E5%85%B6%E4%BB%96%E7%A8%8B%E5%BC%8F%E4%B8%8D%E5%90%8C%E4%B9%8B%E8%99%95-74b02f5c16f1

**Comment by Luck626kkk** [comment]
學號：10446012
文章網址：https://medium.com/@aaa26905677a/%E5%AD%B8%E5%88%B0%E6%96%B0%E7%9A%84%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80ruby-33053989a5e0

**Comment by ting434252** [comment]
學號：10536008
文章網址：
https://medium.com/@ting434252/%E7%B0%A1%E5%8C%96%E7%9A%84%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80-ruby-da836d20877d

**Comment by Drunces** [comment]
學號：10446008
文章網址：
https://medium.com/@sq851023/%E5%8F%AA%E8%A6%81%E6%9C%89%E5%BF%83-%E4%BA%BA%E4%BA%BA%E9%83%BD%E5%8F%AF%E4%BB%A5tdd-898a3f136970

**Comment by IffyArt** [comment]
學號：10446007
文章網址：
https://medium.com/@iffyart1234/ruby%E5%AD%B8%E7%BF%92-%E4%BE%86%E8%87%AA%E5%89%8D%E7%AB%AF%E7%9A%84%E5%A5%87%E6%80%AA%E5%B7%A5%E7%A8%8B%E5%B8%AB-b579100cf8e7

**Comment by 10446014** [comment]
學號：10446014
文章網址：
https://medium.com/@10446014/ruby%E8%88%87java%E7%9A%84%E5%B7%AE%E7%95%B0-67edcf7d7ad9

**Comment by s920613a** [comment]
學號：10636008
文章網址：https://medium.com/@s920613a/ruby%E7%9A%84%E4%B8%8D%E5%90%8C-8e438c79d1c0

**Comment by chiiien** [comment]
學號：10636005
文章網址：https://medium.com/@chiiien9649/%E4%B8%8D%E4%B8%80%E6%A8%A3%E7%9A%84-ruby-904717414867

**Comment by JiaWeiXie** [comment]
學號：10446005
文章網址：https://medium.com/@10446005/ruby-%E8%88%87-swift-a2199ca46726
